### WebScraping Process to Find Covid-19 Data by Country

In [1]:
import requests
import urllib.request
import time
from bs4 import BeautifulSoup

In [2]:
url = 'https://www.worldometers.info/coronavirus/#countries'
response = requests.get(url)

In [3]:
soup = BeautifulSoup(response.text, 'html.parser')
response

In [4]:
table_labels =  soup.find("table", attrs={"id": "main_table_countries_today"})
table_labels_data = table_labels.find_all("td")

In [5]:
# filtering the data that I will going to be using in my table
extract = table_labels_data[121:3329]

In [8]:
#Creating the list of countries
extract = table_labels_data[121:3329][::15]
country_list = []
for x in extract:
    country_list.append(x.get_text().replace('\n', ''))

In [9]:
#Total Cases list
extract = table_labels_data[122:3329][::15]
total_cases = []
for x in extract:
    total_cases.append(x.get_text().replace('\n', '').replace(',', ''))

    
total_cases_copy = []
for x in total_cases:
    total_cases_copy.append(float(x))

In [10]:
#New Cases list
extract = table_labels_data[123:3329][::15]
new_cases = []
for x in extract:
    new_cases.append(x.get_text().replace('\n', '').replace('+', '').replace(',', ''))
    
new_cases_copy = []
for x in new_cases:
    if x == '':
        x = None
        new_cases_copy.append(x)
    else:
        new_cases_copy.append(float(x))

In [11]:
#Total Deaths list
extract = table_labels_data[124:3329][::15]
total_deaths = []
for x in extract:
    total_deaths.append(x.get_text().replace('\n', '').replace(',', ''))
    
    
total_deaths_copy = []
for x in total_deaths:
    if x == ' ':
        x = None
        total_deaths_copy.append(x)
    else:
        total_deaths_copy.append(float(x))

In [12]:
#New Deaths list
extract = table_labels_data[125:3329][::15]
new_deaths = []
for x in extract:
    new_deaths.append(x.get_text().replace('\n', '').replace(',', '').replace('+', ''))
    
    
new_deaths_copy = []
for x in new_deaths:
    if x == '':
        x = None
        new_deaths_copy.append(x)
    else:
        new_deaths_copy.append(float(x))

In [13]:
#Totaled Recovered list
extract = table_labels_data[126:3329][::15]
total_recovered = []
for x in extract:
    total_recovered.append(x.get_text().replace('\n', '').replace(',', '').replace('+', ''))

    
total_recovered_copy = []
for x in total_recovered:
    if x == '' or  x == "N/A":
        x = None
        total_recovered_copy.append(x)
    else:
        total_recovered_copy.append(float(x))

In [14]:
#Active Cases list
extract = table_labels_data[127:3329][::15]
active_cases = []
for x in extract:
    active_cases.append(x.get_text().replace('\n', '').replace(',', '').replace('+', ''))

    
active_cases_copy = []
for x in active_cases:
    if x == '' or  x == "N/A":
        x = None
        active_cases_copy.append(x)
    else:
        active_cases_copy.append(float(x))

In [15]:
#Serious Critical list
extract = table_labels_data[128:3329][::15]
serious_critical = []
for x in extract:
    serious_critical.append(x.get_text().replace('\n', '').replace(',', '').replace('+', ''))

    
serious_critical_copy = []
for x in serious_critical:
    if x == '':
        x = None
        serious_critical_copy.append(x)
    else:
        serious_critical_copy.append(float(x))

In [16]:
#Total Cases/1M Pop list
extract = table_labels_data[129:3329][::15]
total_cases_per_mil = []
for x in extract:
    total_cases_per_mil.append(x.get_text().replace('\n', '').replace(',', '').replace('+', ''))


total_cases_per_mil_copy = []
for x in total_cases_per_mil:
    if x == '':
        x = None
        total_cases_per_mil_copy.append(x)
    else:
        total_cases_per_mil_copy.append(float(x))

In [17]:
#Deaths/1M Pop list
extract = table_labels_data[130:3329][::15]
deaths_per_mil = []
for x in extract:
    deaths_per_mil.append(x.get_text().replace('\n', '').replace(',', '').replace('+', ''))


deaths_per_mil_copy = []
for x in deaths_per_mil:
    if x == '':
        x = None
        deaths_per_mil_copy.append(x)
    else:
        deaths_per_mil_copy.append(float(x))

In [18]:
#Total Tests list
extract = table_labels_data[131:3329][::15]
total_tests = []
for x in extract:
    total_tests.append(x.get_text().replace('\n', '').replace(',', '').replace('+', ''))


total_tests_copy = []
for x in total_tests:
    if x == '':
        x = None
        total_tests_copy.append(x)
    else:
        total_tests_copy.append(float(x))

In [19]:
#Tests/1M Pop list
extract = table_labels_data[132:3329][::15]
tests_per_mil = []
for x in extract:
    tests_per_mil.append(x.get_text().replace('\n', '').replace(',', '').replace('+', ''))

    
tests_per_mil_copy = []
for x in tests_per_mil:
    if x == '':
        x = None
        tests_per_mil_copy.append(x)
    else:
        tests_per_mil_copy.append(float(x))

In [20]:
#Population list
extract = table_labels_data[133:3329][::15]
population = []
for x in extract:
    population.append(x.get_text().replace('\n', '').replace(',', '').replace('+', ''))

    
population_copy = []
for x in population:
    if x == " ":
        x = None
        population_copy.append(x)
    else:
        population_copy.append(float(x))

### Final Data

In [22]:
dataframe_data = {'Total Cases': total_cases_copy , 'New Cases': new_cases_copy, 
                  'Total Deaths':total_deaths_copy, 'New Deaths': new_deaths_copy, 
                  'Total Recovered': total_recovered_copy, 'Active Cases': active_cases_copy, 
                  'Serious Critical': serious_critical_copy, 'Total Cases/ 1M Pop': total_cases_per_mil_copy, 
                  'Death/ 1M Pop': deaths_per_mil_copy, 'Total Tests': total_tests_copy, 
                  'Tests/ 1M Pop': tests_per_mil_copy, 'Population': population_copy}
row_labels = country_list

In [23]:
import pandas
df = pandas.DataFrame(data=dataframe_data, index=row_labels)
len(df)

214

In [24]:
df.head(50)

,Total Cases,New Cases,Total Deaths,New Deaths,Total Recovered,Active Cases,Serious Critical,Total Cases/ 1M Pop,Death/ 1M Pop,Total Tests,Tests/ 1M Pop,Population
USA,1550294.0,NaN,91981.0,NaN,356383.0,1101930.0,16868.0,4687.0,278.0,12300744.0,37188.0,3.307747e+08
Russia,290678.0,NaN,2722.0,NaN,70209.0,217747.0,2300.0,1992.0,19.0,7147014.0,48977.0,1.459273e+08
Spain,278188.0,NaN,27709.0,NaN,196958.0,53521.0,1152.0,5950.0,593.0,3037840.0,64977.0,4.675270e+07
Brazil,255368.0,NaN,16853.0,NaN,100459.0,138056.0,8318.0,1202.0,79.0,735224.0,3462.0,2.123809e+08
UK,246406.0,NaN,34796.0,NaN,NaN,NaN,1559.0,3632.0,513.0,2682716.0,39542.0,6.784424e+07
Italy,225886.0,NaN,32007.0,NaN,127326.0,66553.0,749.0,3735.0,529.0,3041366.0,50294.0,6.047192e+07
France,179927.0,NaN,28239.0,NaN,61728.0,89960.0,1998.0,2757.0,433.0,1384633.0,21218.0,6.525683e+07
Germany,177289.0,NaN,8123.0,NaN,155700.0,13466.0,1133.0,2117.0,97.0,3147771.0,37584.0,8.375286e+07
Turkey,150593.0,NaN,4171.0,NaN,111577.0,34845.0,903.0,1788.0,50.0,1650135.0,19591.0,8.423008e+07
Iran,122492.0,NaN,7057.0,NaN,95661.0,19774.0,2294.0,1461.0,84.0,701640.0,8367.0,8.386264e+07
India,101261.0,933.0,3164.0,8.0,39233.0,58864.0,NaN,73.0,2.0,2404267.0,1744.0,1.378382e+09
Peru,94933.0,NaN,2789.0,NaN,30306.0,61838.0,866.0,2884.0,85.0,661132.0,20085.0,3.291590e+07
Canada,78072.0,NaN,5842.0,NaN,39228.0,33002.0,502.0,2071.0,155.0,1323371.0,35100.0,3.770277e+07
Saudi Arabia,57345.0,NaN,320.0,NaN,28748.0,28277.0,237.0,1650.0,9.0,601954.0,17324.0,3.474733e+07
Belgium,55559.0,NaN,9080.0,NaN,14657.0,31822.0,342.0,4796.0,784.0,696840.0,60157.0,1.158374e+07
Mexico,51633.0,2414.0,5332.0,155.0,35388.0,10913.0,378.0,401.0,41.0,177133.0,1376.0,1.287703e+08
Chile,46059.0,NaN,478.0,NaN,20165.0,25416.0,807.0,2412.0,25.0,381011.0,19952.0,1.909669e+07
Netherlands,44141.0,NaN,5694.0,NaN,NaN,NaN,323.0,2577.0,332.0,297347.0,17358.0,1.713049e+07
Pakistan,43966.0,1841.0,939.0,36.0,12489.0,30538.0,111.0,200.0,4.0,400292.0,1817.0,2.203568e+08
Qatar,33969.0,NaN,15.0,NaN,4899.0,29055.0,172.0,11815.0,5.0,161695.0,56241.0,2.875047e+06
Ecuador,33582.0,NaN,2799.0,NaN,3433.0,27350.0,186.0,1907.0,159.0,96536.0,5482.0,1.761023e+07
Switzerland,30597.0,NaN,1886.0,NaN,27600.0,1111.0,57.0,3538.0,218.0,345760.0,39985.0,8.647139e+06
Belarus,30572.0,NaN,171.0,NaN,10130.0,20271.0,92.0,3235.0,18.0,364319.0,38554.0,9.449678e+06
Sweden,30377.0,NaN,3698.0,NaN,4971.0,21708.0,287.0,3010.0,366.0,177500.0,17588.0,1.009186e+07
Portugal,29209.0,NaN,1231.0,NaN,6430.0,21548.0,105.0,2864.0,121.0,652497.0,63970.0,1.020006e+07
Singapore,28343.0,NaN,22.0,NaN,9835.0,18486.0,12.0,4849.0,4.0,246254.0,42132.0,5.844888e+06
Ireland,24200.0,NaN,1547.0,NaN,19470.0,3183.0,54.0,4908.0,314.0,258808.0,52484.0,4.931150e+06
UAE,24190.0,NaN,224.0,NaN,9577.0,14389.0,1.0,2449.0,23.0,1600923.0,162103.0,9.875965e+06
Bangladesh,23870.0,NaN,349.0,NaN,4585.0,18936.0,1.0,145.0,2.0,185086.0,1125.0,1.644930e+08
Poland,18885.0,NaN,936.0,NaN,7628.0,10321.0,160.0,499.0,25.0,636046.0,16804.0,3.785133e+07
Ukraine,18616.0,NaN,535.0,NaN,5276.0,12805.0,240.0,425.0,12.0,232899.0,5322.0,4.376298e+07
Indonesia,18010.0,NaN,1191.0,NaN,4324.0,12495.0,NaN,66.0,4.0,190660.0,698.0,2.731765e+08
Romania,17036.0,NaN,1120.0,NaN,9930.0,5986.0,193.0,885.0,58.0,313621.0,16290.0,1.925192e+07
Israel,16643.0,NaN,276.0,NaN,13253.0,3114.0,52.0,1927.0,32.0,505702.0,58538.0,8.638917e+06
South Africa,16433.0,NaN,286.0,NaN,7298.0,8849.0,119.0,277.0,5.0,475071.0,8022.0,5.921813e+07
Japan,16305.0,NaN,749.0,NaN,11564.0,3992.0,228.0,129.0,6.0,250151.0,1977.0,1.265201e+08
Colombia,16295.0,NaN,592.0,NaN,3903.0,11800.0,136.0,321.0,12.0,201808.0,3971.0,5.081779e+07
Austria,16269.0,NaN,629.0,NaN,14614.0,1026.0,45.0,1808.0,70.0,366069.0,40673.0,9.000366e+06
Kuwait,15691.0,NaN,118.0,NaN,4339.0,11234.0,161.0,3681.0,28.0,248314.0,58251.0,4.262847e+06
Egypt,12764.0,NaN,645.0,NaN,3440.0,8679.0,41.0,125.0,6.0,135000.0,1322.0,1.020940e+08
Dominican Republic,12725.0,NaN,434.0,NaN,6613.0,5678.0,127.0,1174.0,40.0,50108.0,4625.0,1.083489e+07
Philippines,12718.0,NaN,831.0,NaN,2729.0,9158.0,81.0,116.0,8.0,244800.0,2238.0,1.094039e+08
S. Korea,11078.0,13.0,263.0,NaN,9938.0,877.0,55.0,216.0,5.0,765574.0,14934.0,5.126412e+07
Denmark,10968.0,NaN,548.0,NaN,9301.0,1119.0,26.0,1894.0,95.0,463016.0,79971.0,5.789832e+06
Serbia,10699.0,NaN,231.0,NaN,4799.0,5669.0,16.0,1224.0,26.0,185385.0,21208.0,8.741321e+06
Panama,9726.0,120.0,279.0,4.0,6081.0,3366.0,72.0,2258.0,65.0,51105.0,11867.0,4.306425e+06
Czechia,8586.0,NaN,297.0,NaN,5641.0,2648.0,36.0,802.0,28.0,356515.0,33298.0,1.070669e+07
Argentina,8371.0,NaN,382.0,NaN,2625.0,5364.0,154.0,185.0,8.0,105829.0,2344.0,4.514632e+07
Norway,8257.0,NaN,233.0,NaN,32.0,7992.0,18.0,1524.0,43.0,218039.0,40257.0,5.416217e+06
Algeria,7201.0,NaN,555.0,NaN,3625.0,3021.0,22.0,165.0,13.0,6500.0,149.0,4.375277e+07

In [27]:
df.to_csv('final_dataset.csv')